"""empty message

Revision ID: 29914d5ed86a
Revises: 1c41614a6abd
Create Date: 2023-11-05 19:59:54.995737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29914d5ed86a'
down_revision = '1c41614a6abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
